### ISSUE TITLE
Consecutive Randomizations with Same Seed Produce Different Equipment

### ISSUE THREAD

**Issue by EliteSoba** [3snowp7im/SotN-Equipment-Randomizer#1]
I believe what's happening is that `randomizeEquipment` mutates the `equipment` array, namely the `tiles` attribute. On multiple calls to `randomizeEquipment`, you can inspect `equipment[0].tiles.address` and notice that it changes across calls.

I'm not sure if this is related to the bug where sometimes the shop doesn't seem to be randomized.

**Comment by 3snowp7im** [comment]
This should be fixed in https://github.com/3snowp7im/SotN-Equipment-Randomizer/commit/174b3a237090903fc22b9a6e6f5bcca38d0df876

**Comment by EliteSoba** [comment]
oh lol, yeah looks like it. nice snipe
